### ISSUE TITLE
AMI/OVA documentation for ICAP server and K8-rebuild 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-Releases#39]
@svf97, @MaNe2020 as explained by Dinis in call, please start documenting the following:

- How to take a public AMI and deploy it to another AWS organization and region. - The latest can be found here: https://github.com/k8-proxy/GW-Releases/actions
- How to download the OVA and import them in ESXi and virtual box.
- **This for ICAP server and K8-rebuild only**
- This documentation is only on how to deploy and validate (not on how to create the AMI/OVA)

include:
- how to start the ICAP server and get port 1344 open to send files to
- how to start the K8_Rebuild (aka FileDrop )and get port 80 and 443 open with FileDrop UI and API
- you can use as a reference what we did a couple of months ago here: https://github.com/k8-proxy/GW-proxy/tree/master/OVAs-creation/OVA-MDs - but that is only for OVA as far as I remember. 

Create a new folder here with this updated documentation: https://github.com/k8-proxy/GW-proxy/tree/master/OVAs-creation/OVA-MDs

**Comment by MaNe2020** [comment]
@svf97 @GINAGC my investigation/thoughts until now:

- AMI can be made public by Modify Image Permissions and it can be easily copied to another region (AMIs>Actions>Copy AMI)
- This can be done via AWS cli also, so probably it can be automated in long run
- If we do not want to make AMI public or we want customer just to operate with OVA, here is the [article](https://documentation.avaya.com/bundle/DeployingAEServicesinIaaSEnvironment_r8.0/page/Importing_the_OVA_for_AMI_conversion.html) about that process also, and we have most of that part explained under https://github.com/k8-proxy/k8-rebuild-folder-to-folder/blob/main/AWS_prerequisites.md

- For deploying OVA into ESXi, I think we have enough info already since we did that multiple times. That should be same. We can just merge whole story in one README
- We should also add data on how to check for latest OVA/AMIs

**Comment by GINAGC** [comment]
@MaNe2020 replying to your previous comment:

- AMI in other regions, yes, this is now going to be automated by Samarth and added to CI. So we will need to update this to the documentation when ready. 
- We need to make the AMI public for the customer, they will need both: AMI in AWS and OVA in ESXi and Virtual box. 

I am thinking that for this Friday's deliverable, we will give them the OVA and public AMI, so we don't need to add the steps to make it public, just the link for them to use it.

**Comment by GINAGC** [comment]
@pranaysahith you will be involved in this process and any update needed for the CI/CD. For now, could you please document how to access management UI after ICAP server is deployed? and also, how the user can access logs.

**Comment by GINAGC** [comment]
@svf97, @MaNe2020 

Now that we have this first version, please move the MD files to the client repo https://github.com/k8-proxy/glasswall-servers-eval **(you can add this on wiki section)**, please do not redirect any link to internal repositories, all documentation needed has to be moved here. 

**I think we need to structure the pages, I suggest the following:**
1.- Create a **prerequisites page** (explaining how to get the AMI and OVA for both, ICAP server and file drop) - I don’t think this will be needed, but let's see. 
2.- The second page should have steps to **Deploying ICAP server with 3 sections** - one section for AWS and one section for ESXi and one for virtual box.
3.- Next page should page steps on **Using ICAP server**: including how to access management UI, how to get logs. @pranaysahith can support providing more information here. 
4.- Next page should page steps on **Using File Drop:** including how to access file drop, how to rebuild files (add some screenshots)

Other:
- do not use the term “SOW” or “K8-rebuild” in any of the places. It should be: ICAP server or File Drop
- Please make sure that usage contains as much information as possible,
- Please make sure usage and deployment pages are tested and all steps are validated.

**Comment by MaNe2020** [comment]
@GINAGC @svf97 
Take a look: https://github.com/k8-proxy/glasswall-servers-eval/wiki
There are 5 pages and we are missing data on usage.

@GINAGC once we complete testing we will fill in the missing parts and add details in case smth is not valid.
