### ISSUE TITLE
AKS delivery - testing and documentation

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/GW-Releases#71]
Placeholder for work on this project.

1.- Samarth and Son Ha to do documentation updates.

2.- Marija, Kerem, and Jurgen, to test step by step and create reference videos to the client. The main goal is to make sure that all steps are clearly documented, that the customer has all the needed commands and information to do an installation without GW assistance. 

**We will track the testing here:** https://docs.google.com/spreadsheets/d/1gbOJJZzuu676Le9oV3bFPoNvmDFofMITG39ojKdIpBo/edit#gid=0

**Final documentation:** TBD

**Comment by MaNe2020** [comment]
@aduvukace documentation will be finalized by Monday and we will start working on it next week.
The work is split to cover centOS (me), WIN (Jurgen) and MAC (Kerem).

**Comment by Lestat06** [comment]
@aduvukace testing the documentation whilst doing videos for each step

**Comment by kerempg** [comment]
testing the given documentation for mac environment

**Comment by samarthdd** [comment]
I am getting following error with new code (refer attached  image). This is mostly due to overlapping cluster of icap and file-drop modules. I have seen similar when trying to deploy 9 cluster. 
File modification changes using tfvars is completed. I am taking only suffix and region from tfvars and using it everywhere and passing parameters to scripts as well within terraform.We can review today and merge this.(https://github.com/k8-proxy/icap-aks-delivery/tree/tfvar_changes)
Port customization for only ICAP is completed where port value can be given in tfvars
Doc is still pending, need to merge few changes from Jurgen and Kerem
Customer Certificate workaround - This is done,Currently i am taking a bool  flag from tfvars and according to that terraform will decide to use self signed ssl or customer cert. We can go through this today and ready to merge

**Comment by hongson1981** [comment]
Testing the newest document from @samarthdd ,
Investigate how to config variable of get-kube-context.sh script

**Comment by MaNe2020** [comment]
@aduvukace completed testing.
Created commit for changes on CentOS deployment and added steps for GIT.

**Comment by GINAGC** [comment]
@MaNe2020, @Lestat06, @kerempg for tomorrow Friday, please continue with AKS testing, testing the uninstall steps and install again. 

@samarthdd please try to deploy the 9 clusters.

**Comment by kerempg** [comment]
proceeding with uninstall & installation steps

**Comment by Lestat06** [comment]
@aduvukace testing in windows is in pause for the moment till a solution is found. I will continue testing in centOS

**Comment by MaNe2020** [comment]
@aduvukace have permission issue with glasswall azure account, trying to resolved that and will retest everything once possible
